### ISSUE TITLE
Can't connect to leshan in PSK mode.

### ISSUE THREAD

**Issue by BenGant** [ARMmbed/mbed-client#100]
Can't connect to new version leshan in PSK security mode.
Leshan prints error message:
"INFO: Aborting handshake with peer [/127.0.0.1:32782]: Server does not support any of the client's preferred server certificate types"

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-424

**Comment by yogpan01** [comment]
Hi, The client uses mandatory PSK cipher suites as defined in OMA LWM2M specification
1)TLS_PSK_WITH_AES_128_CCM_8 
2)TLS_PSK_WITH_AES_128_CBC_SHA256
Can you please share your code snippet , where you are setting the M2MRSecurity object with the PSK credentials ? I can verify if there is anything missing from that.

**Comment by BenGant** [comment]
Sure.
http://pastebin.com/7ugRiVxi

**Comment by brolhab** [comment]
Hi BenGant, 
have you finally found why you got the error message ("INFO: Aborting handshake with peer [/127.0.0.1:32782]: Server does not support any of the client's preferred server certificate types") ?
I tried on my side and got the same result. It seems that the cert_type extension is not present in 2nd "Client Hello" handshake frame. This triggers the exception thrown according to the source code of "Leshan Server".
Is it possible to share your code again  please (the link is deprecated ;-)) ?

**Comment by yogpan01** [comment]
Client supports the above given PSK keys only, the Leshan server MUST support those as those are defined in LWM2M specs.
