### ISSUE TITLE
Create object instance problem

### ISSUE THREAD

**Issue by lotuseater24** [ARMmbed/mbed-client#102]
There is problem with creation of object instance. When I call CREATE operation on server with some resource values, it looks like instance is created, but when I call READ operation on created object instance or its resources, it says that either resource not found or operation not allowed.

I've found, what causes the problem.
When we invoke CREATE with instance id, say 99, in M2MNsdlInterface::received_from_server_callback an object instance with given instance id 99 created, after that object->handle_post_request is called, where yet another object instance created, but with the first not used instance id (e.g. 1, if before that there was exactly one object instance with inst. id 0) and fills that object instance with deserialized resources.

The problem may be fixed by removing creation of object instance in M2MNsdlInterface::received_from_server_callback, passing appropriate instance id to object->handle_post_request and creating object instance with that id (instead of instance with first free id) inside object->handle_post_request.

**Comment by yogpan01** [comment]
Thanks for reporting ! We will check this and fix it accordingly.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-428

**Comment by yogpan01** [comment]
Hi, this is fixed , can you please check if this works better now ?

**Comment by lotuseater24** [comment]
Hi, it does work better now, but not totally. Currently object instance created successfully, read for its resources works. But when I reload server's webpage, that object instance disappears, likely to instance id issue, that I described above. It doesn't dissapear (after reloading) with the fix, that I've proposed in the last paragraph above.

Here is code in object.cpp:
sn_coap_hdr_s* M2MObject::handle_post_request(nsdl_s *nsdl,
                                              sn_coap_hdr_s *received_coap_header,
                                              uint32_t instance_id_to_create,
                                              M2MObservationHandler *observation_handler) {
.....
          if(COAP_MSG_CODE_RESPONSE_CHANGED == msg_code) {
                        bool obj_instance_exists = object_instance(instance_id_to_create);
                        M2MObjectInstance *obj_instance = nullptr;
                        if (!obj_instance_exists) {
                            obj_instance = create_object_instance(instance_id_to_create);
                        }
.....
}

And here is code in m2mnsdlinterface.cpp:
uint8_t M2MNsdlInterface::received_from_server_callback(struct nsdl_s * nsdl_handle,
                                                        sn_coap_hdr_s *coap_header,
                                                        sn_nsdl_addr_s *address) {
.....
                            int32_t instance_id = atoi(resource_name.substr(slash_found+1,
                                    resource_name.size()-object_name.size()).c_str());
                            M2MBase* base = find_resource(object_name);
                            if(base && (instance_id >= 0) && (instance_id < 65535)) {
                                if(coap_header->payload_ptr) {
                                    M2MObject* object = static_cast<M2MObject*>(base);
                                    coap_response = object->handle_post_request(_nsdl_handle, coap_header, instance_id, this);
.....
}

**Comment by yogpan01** [comment]
Hi, the part missing is sending update registration message after creating the object instance on client side. We have now fixed but the problem with testing on Leeshan server is that, when we are publishing Update message , we will only be sending the newly created object instance URI , which replaces the existing resource structure on web UI side, which I think is a bug on the server side. But in the meantime, we will test this a bit more and publish client side fix.

**Comment by lotuseater24** [comment]
Hi, seems like it is fixed in newest version. Perhaps, because of  added call of send_update_registration in M2MNsdlInterface::send_to_server_callback.
Thank you, I guess, you may close the issue.

**Comment by yogpan01** [comment]
Yes, we released that yesterday. I will close this issue now. Thanks for your reporting !
