### ISSUE TITLE
"execute" operation on a resource can't return payload

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-client#106]
From page 65 of OMA Lightweight Machine to Machine Technical Specification:

> A Resource is Executed by sending a CoAP POST to the corresponding path. The request MAY include a list of arguments as value of the payload expressed in Plain Text format. The definition of the Executable Resource and its arguments is given in Appendix D.
The list of argument can be empty, 2 arguments of the arguments list are separated by a comma. The syntax of the arguments is provided in Section Execute (5.2.3)
__Note that the behaviour of the “Execute” operation, whether it uses arguments and how those are interpreted, and how it returns values is specified in the Resource description of the Object.__

Since there is not more details there about how those _return values_ could be handled, I dug in the RFC 7252 CoAP ietf draft. In section 5.2 piggybacked and separate responses are discussed, so it's possible. But if I check the code in __m2mresource.cpp__

```cpp
sn_coap_hdr_s* M2MResource::handle_post_request(nsdl_s *nsdl,
                                                sn_coap_hdr_s *received_coap_header,
                                                M2MObservationHandler */*observation_handler*/)
{
    tr_debug("M2MResource::handle_post_request()");
    sn_coap_msg_code_e msg_code = COAP_MSG_CODE_RESPONSE_CHANGED; // 2.04
    sn_coap_hdr_s * coap_response = sn_nsdl_build_response(nsdl,
                                                           received_coap_header,
                                                           msg_code);
    // process the POST if we have registered a callback for it
    if(received_coap_header) {
        if ((operation() & SN_GRS_POST_ALLOWED) != 0) {
            void *arguments = NULL;
            if(received_coap_header->payload_ptr) {
                if(received_coap_header->payload_ptr) {
                    arguments = (void*)malloc(received_coap_header->payload_len+1);
                    if (arguments){
                        memset(arguments, 0, received_coap_header->payload_len+1);
                        memcpy(arguments,
                            received_coap_header->payload_ptr,
                            received_coap_header->payload_len);
                    }
                }
            }
            tr_debug("M2MResource::handle_post_request - Execute resource function");
            execute(arguments);
            free(arguments);
        } else { // if ((object->operation() & SN_GRS_POST_ALLOWED) != 0)
            tr_error("M2MResource::handle_post_request - COAP_MSG_CODE_RESPONSE_METHOD_NOT_ALLOWED");
            msg_code = COAP_MSG_CODE_RESPONSE_METHOD_NOT_ALLOWED; // 4.05
        }
    } else { //if(object && received_coap_header)
        tr_error("M2MResource::handle_post_request - COAP_MSG_CODE_RESPONSE_METHOD_NOT_ALLOWED");
        msg_code = COAP_MSG_CODE_RESPONSE_METHOD_NOT_ALLOWED; // 4.01
    }
    if(coap_response) {
        coap_response->msg_code = msg_code;
    }
    return coap_response;
}
```

Looks like there is no way to define custom responses that could contain return values from an execution of a POST on a resource. 
- Is there a way to handle this that I'm missing?
- Is so, is there example code?
- If not, will the mbed client support such piggybacked responses? will it also support separate responses?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-458

**Comment by yogpan01** [comment]
Hi, normally if you are modifying a dynamic observing resource in the execute callback then the new changed value of the resource will be sent as CoAP notification message. But we can also add the logic of sending updated payload in the POST response.

**Comment by markus-becker-tridonic-com** [comment]
The payload should be part of the response IMHO. Additionally, it should be possible to send separate responses, since some hardware interaction might take longer and is better handled asynchronously. Is that supported at the moment?

**Comment by mlnx** [comment]
@yogpan01 could you please comment on this?

**Comment by yogpan01** [comment]
Hi, payload is not part of the response at the moment but we can add that part. Asynchronously sending the response is not there at the moment and we need to check how we can add that support. But if the resource is an observing resource then the changed value will be sent from the client if it is observed from any service.

**Comment by yogpan01** [comment]
Hi,
There are some new APIs introduced to support this feature.
In M2MResource class , you can use 
` void set_delayed_response(bool delayed_response);` 
to specify that you will send the response later for execute method. By default, this is false, that means when you will receive the POST method then on return ACK, response will contain the payload.

If this is set true, then for POST method, client will send the empty ACK. It is then expected from application that they will decide when to send the response. When the response is ready and new value is set for the resource, application needs to simply call 
`bool send_delayed_post_response();`
on that resource and it will send the updated resource value to the server.

**Comment by javier-moreno-tridonic-com** [comment]
Closing solved issue. Sorry for the delay.
