### ISSUE TITLE
check of _resource_callback != NULL disappeared in recent commit

### ISSUE THREAD

**Issue by lotuseater24** [ARMmbed/mbed-client#111]
In commit ea74c8525ba37a5676a397e4a5984a924f324180 (Fix observation handling)
in file source/m2mresourceinstance.cpp line 217-220
check if (_resource_callback) before its usage was removed.
That leads to crash.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-465

**Comment by anttiylitokola** [comment]
Thanks for your finding. Check is added back in commit https://github.com/ARMmbed/mbed-client/commit/c795e87bef047cc7f59e1f3a3b2b6cba6251802f.
