### ISSUE TITLE
Idle state in Firmware Object, resource State

### ISSUE THREAD

**Issue by sirrko** [ARMmbed/mbed-client#113]
Hello,
regardint to OMA-TS-LightweightM2M-V1_0-20151030-C, in Firmware Object, resource State, values must start from 0 to 2, but in mbedClient it still from 1:
 typedef enum {
       Idle = 1, // Note, that in new OMA spec should be 0.
       Downloading,
       Downloaded
    }

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-466

**Comment by anttiylitokola** [comment]
Thanks for your finding. We will fix this in future releases.
