### ISSUE TITLE
coap_header->content_type_ptr = (uint8_t*)malloc(1);

### ISSUE THREAD

**Issue by lotuseater24** [ARMmbed/mbed-client#115]
In many places the following code repeated:
header->content_type_ptr = (uint8_t*)malloc(1);
Then its value set to, say, 99. And it's freed: 
if( header->content_type_ptr ){
    free(header->content_type_ptr);
    header->content_type_ptr = NULL;
 }
Why not declare  uint8_t (or better uint16_t) content_type in coap_header and use it directly without pointer manipulations? It would be more optimal and readable.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-476

**Comment by anttiylitokola** [comment]
Thank you for your report. We will look in to this.

**Comment by anttiylitokola** [comment]
Hi, we have made some cleanup in following PR:
https://github.com/ARMmbed/mbed-client/pull/178

In this phase we are not going to make any modification to coap_header structure but it's something we will look in the future.
