### ISSUE TITLE
Support READ for all Object

### ISSUE THREAD

**Issue by sirrko** [ARMmbed/mbed-client#127]
Hi,
from **mbed Client Guide** I see that the Client API allows setting values all the Object Instances of an Object (TLV format supported) and mbed DS can then read these values using the Read operation. But in code in m2mobject.cpp I found comment "//TODO: GET for Object is not yet implemented."

Could you please clarify where is updated information?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-513

**Comment by yogpan01** [comment]
Hi, thanks for reporting. That is an old comment which was not removed. The implementation is already done. We will be updating the comment.

**Comment by anttiylitokola** [comment]
Hi, comments are now removed from the latest release.
