### ISSUE TITLE
String vs std::string

### ISSUE THREAD

**Issue by lotuseater24** [ARMmbed/mbed-client#128]
May you clarify, what's the benefit of custom String implementation? (mbed-client/m2mstring.h)
It seems, its public API is a subset of std::string's public API.
Is there any performance/memory benefit?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-512

**Comment by yogpan01** [comment]
Hi , the reason is we are not sure if there would be std libraries available across different platforms, that's why there is a wrapper class for string which would mean that instead of refactoring the complete code we only need to modify one class to handle it. Hope this helps !

**Comment by lotuseater24** [comment]
Hi, thank you. Understood, although it's very strange.
