### ISSUE TITLE
Observation count not being incremeneted

### ISSUE THREAD

**Issue by Areontar** [ARMmbed/mbed-client#130]
Hi guys,

I have a device that has several resource that are marked as observable (the resource is created dynamically, and the boolean is set to true).  The server then sends a GET with observing option on the resources that needs to be observed.

I then set the updated values when needed, and I see that it triggers a message up to the server, but when examining the packets, the obs:<count> in the header is always set to 0.  Maybe I am doing something wrong, but even if set the value or try to override the virtual method, the value is still 0 for all notification.  According to spec, the obs count should be incremented after each notification.

maybe I am doing something wrong, but it seems like the value is not taken into account.

Thanks

Simon

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-525

**Comment by yogpan01** [comment]
Hi, We are fixing this issue , where the observation count will be incremented everytime the notification is sent for a given resource. We will update you once we release the fix. Thanks for reporting !

**Comment by Areontar** [comment]
awesome, thanks!

**Comment by anttiylitokola** [comment]
Hi, we are now incrementing observation count for every sent notification. You can verify functionality using latest release.

**Comment by Areontar** [comment]
Yes i can confirm this is fix in 1.2.18, thanks!
