### ISSUE TITLE
m2mvector erase will access unassigned memory

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-client#140]
I've changed the MORE_SIZE value to 2 (initially space for 32 elements was reserved as far as I understood).

If I have 5 elements in the vector and the debugger displays that:
> _size = 5
> _index = 5 
> _capacity 5

If I try to erase position number 4 (last element in my vector) the following code is executed:
```C++
void erase(int position) {
        if(position <= _size) {
            _object_template[position] = 0;
            _size--;
            if(position < _index) {
                for(int k = position; k < _index; k++) {
                    _object_template[k] = _object_template[k+1];
                }
            }
            _index--;
        }
    }
```
**position**(4) will be in this case smaller than **_size**(5) and **_index**(5) so the method will try to copy on index **[k]** (with value 4, the element I want to erase) the contents of the index **[k + 1]** (unassigned memory).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-554

**Comment by yogpan01** [comment]
Hi, Yes that's an error. We will fix that and release soon. Thanks for reporting.

**Comment by yogpan01** [comment]
This should be now fixed. Can you check and verify if it is working for you ?

**Comment by anttiylitokola** [comment]
Fix is published so I'll close this ticket.
