### ISSUE TITLE
resources are not observable

### ISSUE THREAD

**Issue by kaishi78** [ARMmbed/mbed-client#148]
When running 1.2.19 mbed-client, i set the observable parameter to true when creating the resource and I would be able to see that the resource is observable at the device server.  However, when I updated to 1.3.1, the resource is now not observable at the device server.  With the latest update, is there an api I have to update to make the resource observable.  

Thanks in advance.

Kai

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-571

**Comment by yogpan01** [comment]
Hi, Please do the yotta update to fetch the latest libraries. This should now work if you have any resource marked observable in your application.
