### ISSUE TITLE
can't connect to bootstrap server

### ISSUE THREAD

**Issue by kaishi78** [ARMmbed/mbed-client#155]
running mbed-client 1.4.1, not able to connect to mbed bootstrap server.

**Comment by yogpan01** [comment]
Bootstrap feature is not official supported by mbed Client at the moment.

**Comment by kaishi78** [comment]
Is there any schedule when this will be support?  

Thanks for your help in advance.

Kai

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-589

**Comment by yogpan01** [comment]
HI, We will communicate about the feature release through mbed.com, In the meantime, you can use Device Connector to continue testing other features.
