### ISSUE TITLE
race condition seen in M2MInterfaceImpl::state_register_address_resolved()

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client#156]
A race condition is seen with this code:
```

    internal_event(STATE_REGISTER_RESOURCE_CREATED);
    _connection_handler->start_listening_for_data();
    if(!_nsdl_interface->send_register_message((uint8_t*)event->_address->_address,event->_port, address_type)) {
```

start_listening_for_data() creates a listener thread that eventually calls mbedtls_ssl_flush_output() in the mbedtls module as part of mbedtls_ssl_read(). Similarly, send_register_message() might concurrently call the same function. This is an issue, because of this code in mbedtls_ssl_flush_output():

```
while( ssl->out_left > 0 )
{
         ...

         ret = ssl->f_send( ssl->p_bio, buf, ssl->out_left );
 
         MBEDTLS_SSL_DEBUG_RET( 2, "ssl->f_send", ret );
 
         if( ret <= 0 )
             return( ret );
 
         ssl->out_left -= ret;
}
```

When both threads execute this code concurrently, it is possible for the register message to be sent twice, and for out_left to be decremented past 0, resulting in a very large integer. The code would then transmit erroneous data as a result.

As verification, the issue indeed disappears if the listener thread is created *after* sending the register message:

```
    internal_event(STATE_REGISTER_RESOURCE_CREATED);
    if(!_nsdl_interface->send_register_message((uint8_t*)event->_address->_address,event->_port, address_type)) {
     ...
    }
    _connection_handler->start_listening_for_data();
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-588

**Comment by yogpan01** [comment]
Hi, Thanks for reporting. We are looking into fixing this issue.

**Comment by yogpan01** [comment]
This should now be fixed and released, moved the logic of start_listening_for_data() as suggested. Can you please check if this works fine for you now ?

**Comment by vanti** [comment]
Thank you. This works fine now.
