### ISSUE TITLE
We should be able to write attributes before observing a resource.

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-client#158]
Acording to LWM2M specification for notify (5.5.2). We should be able to set the observe attributes before sending the observe request.

![image](https://cloud.githubusercontent.com/assets/14233019/13282696/8b314664-daea-11e5-856e-c9c99563fd59.png)

As far as I could tell the handling of the the attribute values is done in the respective **handle_put_request** method from **M2MBase** and derivations where **handle_observation_attribute** is called if a query is present.

To do so, at that point in time the **_report_handler** must be already initialized. The problem I see is that **_report_handler**  is only initialized either during assigment/copy of one M2MBase instance. Or in the **M2MBase::set_under_observation** method call.

As far as I understood, this method call will only happen when make an observe request to the resource, therefore making impossible to set the attributes before the observe request.

**Comment by yogpan01** [comment]
Hi,
Yes that's how it has been implemented at the moment. There are few changes we are planning to do related with observation and handling attributes and this is one of them which we will check and fix. We will update when we do this change.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-593

**Comment by javier-moreno-tridonic-com** [comment]
On a unrelated note, trying to hack my way through. I did some small changes to try to set the attributes beforehand when I observed something weird. I got to a point were I run the **M2MReportHandler::set_notification_attribute** method. When I reach the code shown below (which I also modified slightly to test) the values of the following variables are:

**option** *"pmin=10.0"* 
**attribute** *"pmin\0"* 
**attribute** *"10\0"* 

```Cpp
if (strcmp(attribute, PMIN.c_str()) == 0) {
    	int test = -1;
    	double test2 = -1;
    	int r = -1;
    	r = sscanf(value, "%d", &test);
    	r = sscanf(value, "%lg", &test2);
        r = sscanf(value, "%f", &_pmin);
        success = true;
        _attribute_state |= M2MReportHandler::Pmin;
        tr_debug("M2MReportHandler::set_notification_attribute %s to %f read %d", attribute, _pmin, r);
    }
```

Nevertheless only the first sscanf works, filling **test** with value *10*. 
I'm currently using the version 4.9_2015q1 of the GNU Tools ARM Embedded.

Is there any reported misbehavior of the sscanf function?
Is there any better place to post this secondary issue?

**Comment by yogpan01** [comment]
Hi, That's strange behaviour because we have tests where we are passing pmin=10.0 and it works correctly. We will need to check this again. Of late, there has been issue with using float on some compilers.

**Comment by javier-moreno-tridonic-com** [comment]
Thanks for the heads up. For completion, I updated the previous comment (I was mixing 10.0 and 10) also just add that I tried using "pmin=10" (and other random values with and without **"."**) with no luck.

**Comment by anttiylitokola** [comment]
Hi, It's should be possible to write attributes before the observation is started, at least I got it working nicely. M2MBase::set_under_observation is called when ever resource is created in M2MNsdlInterface class so report handler should exist when handle_put_request is called.

There is also fix for float type handling. Can you try out and see is the mbed-client version 1.4.4 working any better?

**Comment by anttiylitokola** [comment]
Hi, I'll close this ticket since no response, but feel free to open it again or create new one if you have any further questions.
