### ISSUE TITLE
porting guide doesn't define "mbed-client-<your-platform-name>" clearly

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-client#159]
The usage of the term 'platform' is not clear in the porting guide.  In mbed, this typically refers to a target board.  However, in the case of the porting guide, the term platform seems to refer to the OS (i.e. mbed OS or Linux).  If someone wants to port mbed-client to their target platform (board), yet still run it on mbed OS, then the porting steps are very different.  This has caused some confusion.  I recommend providing two sections in the guide - one for porting to another OS, and one for porting to another board (which must already have a mbed OS port, but may have a new and different network interface).

**Comment by yogpan01** [comment]
Agreed that there can be better documentation explaining how to add support for more target boards and network interfaces, but that should go to may be "sal" layer documentation and cross referenced from mbed Client's porting guide. What do you think about this ? @bremoran @maclobdell @peknis01

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-595

**Comment by yogpan01** [comment]
There will be new proposed way for porting mbed client. Which will be released soon.
