### ISSUE TITLE
Maximum Packet size coap

### ISSUE THREAD

**Issue by martin-tomasini-tridonic-com** [ARMmbed/mbed-client#173]
Hello,

I hope  this is the right repo for my question. Otherwise please let me know. 
We need to send a huge block of data (several kbytes) to our devices over coap/lwm2m. 
We will split this huge block of data into smaller packets on application layer (lw2m2).
But we would to avoid to have to split this data into a endless number of packets with just a few bytes size.
So here my questions: 
- Is the coap layer in mbed supporting block transfers & segmentation?
- Whats the maximum payload size for coap packets  the mbed stack can deal with?
- May it be possible to influence this value by redefining buffer sizes, defines etc?
- If yes, where?

Thanks in advance for your help.

Kind Regards

Martin Tomasini

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-643

**Comment by anttiylitokola** [comment]
Hi, we have just published new documentation which talks also about blockwise functionality and how to take it into use. Please, check the documentation from following link:
https://docs.mbed.com/docs/mbed-client-guide/en/latest/Introduction/

I'll close this issue now but do not hesitate to open it again if you have any further questions.
