### ISSUE TITLE
Tlv deserializer error

### ISSUE THREAD

**Issue by BenGant** [ARMmbed/mbed-client#180]
It seems that your deserializer decode multiple resources type incorrrectly:

In function:

bool M2MTLVDeserializer::is_multiple_resource(uint8_t *tlv, uint32_t offset)

 ret = (TYPE_MULTIPLE_RESOURCE == (tlv[offset] & TYPE_RESOURCE));

instead:

ret = (TYPE_MULTIPLE_RESOURCE == (tlv[offset] &TYPE_MULTIPLE_RESOURCE));

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-652

**Comment by anttiylitokola** [comment]
Thanks for the report and sorry for the delay. TYPE_RESOURCE(0xC0, 11000000) is the correct mask in this case. For example same mask is used in wakaama project.
https://github.com/eclipse/wakaama/blob/master/core/tlv.c#L33
