### ISSUE TITLE
 LWM2M client does not always return the instance ID

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#208]
Posting a CoAP message with Leshan (execute type opaque) without any payload data, m2mresource.cpp does not pass the instance ID to the assigned callback function. We want to process with only one single static callback function all instance executes. So for all object instances we create:
 
            res->set_execute_function( execute_callback( this,                           
                     &ControllerObject::iControl_execute_our_callback_function ) );
 
So for example the message  "6003/2/105", object 6003, instance 2, resource 105 and no payload data, the callback function called for resource 105 needs to know the instance number (=2). The current m2mresource.cpp implementation copies this required info into the *exec_params instance if ( received_coap_header->payload_ptr ) is positive. If not the exec_params is passed as NULL to the callback function.
 
 
                        if(received_coap_header->payload_ptr) {
                           …
                             exec_params->_object_name = object_name();
                             exec_params->_resource_name = name();
                             exec_params->_object_instance_id = object_instance_id();
 
Can you please implement to pass the instance ID anyway when it is available or propose a solution to obtain the instance ID. Thanks in advance.

**Comment by yogpan01** [comment]
Hi , this link can provide some information for your query
https://docs.mbed.com/docs/mbed-client-guide/en/latest/dev_man_serv_enable/#the-execute-operation
We have APIs for callback function from which you can get the instance Id and other resource name information.
Please let us know if this solve your issue.

**Comment by EduardPon** [comment]
Hello,

Yes I'm aware about the API's. The snippets in your link is also an example with payload, and this works fine. But the ID info I require is not passed when **no payload** is available. I don't mind either if it is passed via an extra parameter in the callback function.

If payload is available then the following implementation to get the ID this works great. But without arguments == NULL.

    void controllerObject::iControl_execute_our_callback_function( void *arguments )
    {
        M2MResource::M2MExecuteParameter *exec_params = (M2MResource::M2MExecuteParameter *) arguments;
        if( exec_params )   {
            int id = (int)( exec_params->get_argument_object_instance_id() );
        }
        /// do your execute processing with instance ID!
    }

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-718

**Comment by yogpan01** [comment]
Hi, we will fix the issue so that you can get the instance ID info even if there is no payload. 
Thanks for reporting. We will update this issue ticket, when we release the fix.

**Comment by anttiylitokola** [comment]
Hi,

This is now fixed and path of the object is now part of the execute parameters also if the payload is empty. Fix is available in mbed-client version 1.10.1.

**Comment by EduardPon** [comment]
Hello,

I have verified your update and can confirm it works. Thanks!
