### ISSUE TITLE
FP1<void,M2MExecuteParameter*> execute_callback;

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client#245]
The signature of
    `typedef FP1<void,void*> execute_callback;`
should not use void*, but a M2MExecuteParameter. Lately this was silently changed from coap_header_t to M2MExecuteParameter and that change wasn't noticed by the compiler breaking our LWM2M resources for Execute.

**Comment by yogpan01** [comment]
Hi,
Was the coap_header_t your own implementation, because we introduced M2MExecuteParameter some time back, before that it was just void*  . The idea was not to break the API signature, you might have used it to map it for your own defined structure but you can now move to M2MExecuteParameters

**Comment by markus-becker-tridonic-com** [comment]
Yes, this was our extension and I accidentally put this in the issue description.

With the change you were breaking existing objects, then it's better to change the API rather than silently break, or?

**Comment by yogpan01** [comment]
Yes , thats a good point. It didnt break anything on our end but yes application building their own logic would have impact. We will ensure that future updates will result in major API version change, if it breaks anything on application side as well.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-830
