### ISSUE TITLE
Observation while re-connecting

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client#269]
It seems that if a resource is being observed and the stack is being brought down and re-connecting, and an observation is to be sent during re-connection hard faults are happening.

See the following stack trace:
![](https://git.dev.zgrp.net/stc/tri-stc-sensor/uploads/1c8900855f8595d52d5bf5f0211073e2/sensor-hard-fault-after-commod-not-answering_2016-06-21_11-23-50.jpg)

Can the sending of observations be guarded against the re-connection logic?

@mlnx
@daniel-cesarini-tridonic-com

**Comment by yogpan01** [comment]
Hi, we will check and fix this issue.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-881

**Comment by anttiylitokola** [comment]
Hi, we've been trying to reproduce this in our end but no luck yet. Are you seeing this crash every time when trying to send observation when stack is in re-connection mode and is it the first observation which causes the crash?

**Comment by markus-becker-tridonic-com** [comment]
@ivan-adzic-tridonic-com

**Comment by markus-becker-tridonic-com** [comment]
Thanks. Tried again with updated mbed-client, we can't reproduce it at the moment either. Will re-open, if it happens again.
