### ISSUE TITLE
TLV encoding not supported for put requests on resource instances 

### ISSUE THREAD

**Issue by dkrupp** [ARMmbed/mbed-client#300]
Testing against leshan server revealed that mbed client does not handle put request for resource instances if the message is TLV encoded.
COAP_MSG_CODE_RESPONSE_UNSUPPORTED_CONTENT_FORMAT error code is returned to the sender.

Th error stems from m2mresourceinstance.cpp:
...
                tr_debug("M2MResourceInstance::handle_put_request() - Request Content-Type %d", coap_content_type);

```
            if(COAP_CONTENT_OMA_TLV_TYPE == coap_content_type) {
                msg_code = COAP_MSG_CODE_RESPONSE_UNSUPPORTED_CONTENT_FORMAT;
            } else {
```

---

https://github.com/ARMmbed/mbed-client/blob/master/source/m2mresourceinstance.cpp#L457

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1048

**Comment by yogpan01** [comment]
Hi,
We support TLV encoding of value 99. Since there are no standard encoding value defined for TLV yet we are not supporting Leshan enabled TLV value.

**Comment by dkrupp** [comment]
Of course, I set the TLV encoding to 1542  to be compatible with leshan and it still does not work. Please check your code. Please reopen the case.

**Comment by yogpan01** [comment]
Hi,
The current implementation support only 8 bit values for content type checks. 
I will re-open the issue but unfortunately this issue will not be fixed anytime soon as we would need to change the API signature and this might break some existing clients. We will update the issue once we fix it to support Leshan content type as well.
Sorry for inconvenience.

**Comment by dkrupp** [comment]
Hi,
as I understand there are 2 problems here.
1) m2mbase.h M2MBase::_coap_conent_type is only 8 bit wide, however it should be 16 bits.  According to https://tools.ietf.org/html/rfc7252 Table 4. coap Content-Format option can be 0-2 bytes.

2) the implementation for decoding PUT request for resource instances is simply not implemented by your code.
Again, please check this line https://github.com/ARMmbed/mbed-client/blob/master/source/m2mresourceinstance.cpp#L457

The problem is reproducible by setting TLV_CODE in leshan to 99 (same as mbed-client is using) and issuing a put request against a resource instance. The response from mbedclient is Constrained Application Protocol, Acknowledgement, 4.15 Unsupported Content-Format, MID:26595.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
