### ISSUE TITLE
Device Object not displaying properly on the Portal

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/mbed-client#345]
I need to change this function call to ```true``` in order for the Device Object to appear properly in the Portal:

https://github.com/ARMmbed/mbed-client/blob/master/source/m2mdevice.cpp#L151

**Comment by marcuschangarm** [comment]
@TeroJaasko @anttiylitokola @jankii01

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1284

**Comment by marcuschangarm** [comment]
Fixed by:

https://github.com/ARMmbed/mbed-cloud-client/pull/88
