### ISSUE TITLE
Basic LWM2M device management via serial port

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-client#398]
My understanding of LWM2M is still incomplete.

For debug and learning purposes I'm interested in using a serial port to manage resources provided by devices running mbed-client.

http://dev_devtoolkit.openmobilealliance.org/IoT/LWM2M10/doc/TS/index.html#!Documents/plaintext.htm

I'd like to stick to using the plaintext or json data formats to keep things portable and mostly human readable.
Taking this approach, is an attempt to avoid implementing an AT command set or other ipc interface.

Is this something that would be feasible to do?
I'm still trying to get a picture of whether the LWM2M specification prevents, facilitates, allows, or doesn't forbid this concept as well.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1420

**Comment by teetak01** [comment]
@loverdeg-ep if you want to do some command line handling, we do have this library (https://github.com/ARMmbed/mbed-client-cli) which allows you to implement it, although its mainly used by internal tools and we do not provide any too useful README's for it. Implementing some serial-control is probably relatively complicated task just for understanding the LWM2M.

If you are trying to figure out LWM2M, I would suggest starting with our example application (https://github.com/ARMmbed/mbed-os-example-client). When connected via serial, you can follow the program logic from there. Just enable mbed-trace from mbed_app.json. I would also suggest first using the application via connector.mbed.com. It allows you to remote control your endpoint via REST-commands. Generally that is what the LWM2M Client is really designed for. We use the cli-library internally for test-automation.

**Comment by teetak01** [comment]
Closing due inactivity.
