### ISSUE TITLE
Hard fault caused by retry action to register 

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#408]
In the function __nsdl_c_received_from_server (nsdlaccesshelper.cpp), the free(coap_header->payload_ptr) causes a HardFault. I can reproduce this with the following situation:

- Enable CoAP block transfer << Important to do!!.
- No LWM2M server is available on the network.
- Start the LWM2M client.
- After a number of registration attempts, __nsdl_c_received_from_server is called and wants to free payload_ptr address that has presumably already been freed. 

In the code the following comment states: 

> Payload freeing must be done in app level if blockwise message

And because we enabled the CoAP block wise transfer, I would expect the conditional free call should been skipped.

Copy of function:
```
uint8_t __nsdl_c_received_from_server(struct nsdl_s * nsdl_handle,
                                      sn_coap_hdr_s *coap_header,
                                      sn_nsdl_addr_s *address_ptr)
{
    uint8_t status = 0;
    M2MNsdlInterface  *interface = get_interface(nsdl_handle);
    if(interface) {
        status = interface->received_from_server_callback(nsdl_handle,
                                                                 coap_header,
                                                                 address_ptr);
        // Payload freeing must be done in app level if blockwise message
        if (coap_header &&
                coap_header->options_list_ptr &&
                coap_header->options_list_ptr->block1 != -1) {

            free(coap_header->payload_ptr);
            coap_header->payload_ptr = NULL;

        }
    }
    return status;
}

```

Call stack, breakpoint before free is executed:
```
Thread #1 1 (Thread mode) [core: 0] (Suspended : Breakpoint)	
	__nsdl_c_received_from_server() at nsdlaccesshelper.cpp:86 0x6351c	
	coap_rx_callback() at sn_grs.c:92 0x67d4c	
	sn_coap_protocol_exec() at sn_coap_protocol.c:768 0x664ec	
	sn_nsdl_exec() at sn_nsdl.c:1.024 0x69b68	
	M2MNsdlInterface::timer_expired() at m2mnsdlinterface.cpp:709 0x5942c	
	M2MTimerPimpl::timer_expired() at m2mtimerpimpl.cpp:175 0x54564	
	tasklet_func() at m2mtimerpimpl.cpp:59 0x5419e	
	eventOS_scheduler_dispatch_event() at event.c:292 0x6e7ac	
	eventOS_scheduler_run() at event.c:317 0x6e7ca	
	event_loop_thread() at ns_event_loop.c:76 0x6cb10	
	<...more frames...>	
```
Content of coap_header variable:
```
coap_header	sn_coap_hdr_s *	0x20028aa8	
	token_len	uint8_t	0 '\0'	
	coap_status	sn_coap_status_e	COAP_STATUS_BUILDER_MESSAGE_SENDING_FAILED	
	msg_code	sn_coap_msg_code_e	COAP_MSG_CODE_REQUEST_POST	
	msg_type	sn_coap_msg_type_e	COAP_MSG_TYPE_CONFIRMABLE	
	content_format	sn_coap_content_format_e	COAP_CT_NONE	
	msg_id	uint16_t	440	
	uri_path_len	uint16_t	2	
	payload_len	uint16_t	512	
	token_ptr	uint8_t *	0x0 <__isr_vector>	
	uri_path_ptr	uint8_t *	0x20027a08 "rdÿ\037ø\227\002 \020"	
	payload_ptr	uint8_t *	0x200298b9 "</5001/0/911>,</5001/0/910>,</5001/0/902>,</5001/0/120>,</5001/0/119>,</5001/0/118>,</5001/0/117>,</5001/0/922>,</5001/0/922/3>,</5001/0/922/2>,</5001/0/922/1>,</5001/0/922/0>,</5001/0/108>,</5001/0/1"...	
	options_list_ptr	sn_coap_options_list_s *	0x20029650	
		etag_len	uint8_t	0 '\0'	
		use_size1	unsigned int	1	
		use_size2	unsigned int	0	
		proxy_uri_len	uint16_t	0	
		uri_host_len	uint16_t	0	
		location_path_len	uint16_t	0	
		location_query_len	uint16_t	0	
		uri_query_len	uint16_t	57	
		accept	sn_coap_content_format_e	COAP_CT_NONE	
		max_age	uint32_t	60	
		size1	uint32_t	2815	
		size2	uint32_t	0	
		uri_port	int32_t	-1	
		observe	int32_t	-1	
		block1	int32_t	13	
		block2	int32_t	-1	
		proxy_uri_ptr	uint8_t *	0x0 <__isr_vector>	
		etag_ptr	uint8_t *	0x0 <__isr_vector>	
		uri_host_ptr	uint8_t *	0x0 <__isr_vector>	
		location_path_ptr	uint8_t *	0x0 <__isr_vector>	
		location_query_ptr	uint8_t *	0x0 <__isr_vector>	
		uri_query_ptr	uint8_t *	0x20029788 "ep=Open 12:42:1a:a3:0b:01&et=test&lt=3600&d=DOMAIN&b=U"	
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1476

**Comment by JaniSuonpera** [comment]
What target hardware you are using? K64F or other hardware?
What compiler you are using and which version? GCC_ARM, iAR or ARMCC?
How long time it takes to get HardFault?
How you are prevent connetion to LWM2M server?
Are you using secure connection? 
Are you using e.g. https://github.com/ARMmbed/mbed-os-example-client or some other public repository?
Do you have other information for me like modifications to SW,  etc.?

**Comment by JanneKiiskila** [comment]
Hi, @EduardPon  - can you please share the details of your setup? We've not been able to reproduce the issue locally.

Best Regards,

Janne

**Comment by EduardPon** [comment]
Hello,

I assume that the outdated version (September 2016) I'm currently using, is not representative. I want to merge the latest LWM2M client version into our system and try to reproduce the issue. Next I will update this issue report.

Best regards, 
Ed

**Comment by JanneKiiskila** [comment]
Hi @EduardPon 

Ok, yes - we've done quite a few fixes inbetween, so updating to latest is probably a good idea. Let us know how it fans out.

Thanks you & best regards,


Janne

**Comment by JanneKiiskila** [comment]
Hi @EduardPon, any updates on this case?

**Comment by EduardPon** [comment]
We have planned to wait for the official mbed 5.4 release.

**Comment by teetak01** [comment]
@EduardPon mbedOS 5.4.1 in out already.

**Comment by EduardPon** [comment]
Thanks. I was not aware about that. I assume we will start merging it next week.

**Comment by JanneKiiskila** [comment]
Hi,

yes - 5.4.1  RC is out now - https://github.com/ARMmbed/mbed-os/commit/f4864dc6429e1ff5474111d4e0f6bee36a759b1c.

5.4.0 came out via this; https://github.com/ARMmbed/mbed-os/commit/305f5c491e34d86098e9da91b322017549c189ff

**Comment by JanneKiiskila** [comment]
Hi @EduardPon,

any updates on this case?

**Comment by EduardPon** [comment]
Hello,

I have updated environment with the code of mbed-client, mbed-client-c, mbed-client-classic, mbed-coap, mbed-client-mbed-tls and mbed-os repository versions of 24 April. 

**This issue still occurs in exact the same way like the september 2016 version does.**

**Comment by JanneKiiskila** [comment]
Hi @EduardPon ,

can you share the output of `mbed ls` command for your environment? Which compiler are you using, which version and against which server are you testing? We've not been able to reproduce this issue locally yet, so all details helping us reproduce this issue would be greatly appreciated.

Thank you & best regards,


Janne Kiiskilä

**Comment by EduardPon** [comment]
Hello,

We use the GCC compiler (gcc-arm-none-eabi-5_4-2016q2-20160622-win32).
The issue occurs when the server is not reachable.

We have no library links to repositories, but we copied the code from the following repository links:

- mbed-os/#50b3418e45484ebf442b88cd935a2d5355402d7d
- mbed-client/#0bb304ba525ff61198c6b1c8a432e3427c42699c
- mbed-client-c/#c739b8cbcc57d7eab34a176179131f33b4436658
- mbed-client-classic/#612d27a2e8c7fde693c3a6d87deca6d6960d390d
- mbed-client-mbed-tls/#7e1b6d81503843ee98192e11f31df12508938c9d
- mbed-coap/#d9ef058ffece940f4bcc228d4d1beae0ba2c6719
- sal-stack-nanostack/#75c0a88a93f060e7c7019d0e104a5022c94ca925
- pal/#dee4410a7004e64226349b6d1aa8546e85ccae86

**Comment by JaniSuonpera** [comment]
Hi @EduardPon ,

I did not succeed to reproduce the issue locally with mbed-os-example-client and target K64F.  I am using GCC_ARM  Linux compiler (arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 6.2.1 20161205 (release) [ARM/embedded-6-branch revision 243739]). 

Can you provide more information about your environment, configuration etc. ? Can you provide mbed trace logs? I should get to reproduce issue locally.  Have you tried to use https://github.com/ARMmbed/mbed-os-example-client for checking issue?


Thank you & best regards,

Jani Suonperä

**Comment by yogpan01** [comment]
Hi @EduardPon,
Can you please provide some more information for following things
1) Are you using mbed-client in non-secure mode with local Device Server (like Leshan or some other third party server) ?
2) Are you using mbed-client in UDP or TCP mode ?
3) Are you noticing this crash when the client tries to register for the first time or is trying to send registration update and then the server is not available ?

The reason is that , we are not able to reproduce this call stack with simple client failing registration because of unavailability of server. We use mbed-os-example-client which always connect to api.mbed.connector.com:5684 and that server is always available. 
So, you must be having some other configuration that you are able to reproduce "no-server" condiftion easily. If you can share your setup details , we will try to re-produce those locally and hopefully we get the same call-trace.
Regards,
Yogesh

**Comment by EduardPon** [comment]
My answers:
1.Local Leshan server. Secure and none secure (build time configurable).
2.UDP
3.First time registrering

I will try to gather some more debug info.

**Comment by EduardPon** [comment]
Hello,
I have merged one of the latest mbed-client and mbed-client-c. 
After this update, the issue does not occur anymore. 
Thanks for your support.

**Comment by yogpan01** [comment]
Hi @EduardPon 
Nice to know that it works ! Is it possible if you can share which mbed-client-c and mbed-client (github commit ID) are you now working with, which resolved this issue for you ?
Also, would be interesting to know, the github commit IDs for the crashing case.

**Comment by EduardPon** [comment]
Fixed with [mbed-client](https://github.com/ARMmbed/mbed-client/commit/1ab229e13eed8de3b787cf6c4ae58b12908f40dd) and [mbed-client-c](https://github.com/ARMmbed/mbed-client-c/commit/4b8c1c73dcec37caad8309d050bfc814dc0f3a82)

Last merged version that crashes, see comment my of 10 April.
