### ISSUE TITLE
M2MConnectionSecurityPimpl failed

### ISSUE THREAD

**Issue by NadineSueur** [ARMmbed/mbed-client#416]
Hi,

I have linked to this email some debug files (on the mbed client and Border router) I have registered on my platform.
As you will see, the mbed client is able to connect to the network successfully
(The message Connected to Network successfully is displayed), but it looks like the function M2MConnectionSecurityPimpl() never succeed. I do not understand what i'm doing wrong.

I think I need to describe quickly my configuration.
I'm working with FRDM-K64F boards.

I have two platforms . Each platform is made with two K64 boards. The mbed client and the border router are running on K64 boards The border router is connected to the network with an etnernet cable.

I have replaced the atmel_rf_driver by a PLC (power-line communication) driver. (I'm not using the RF technology anymore). The PLC driver is running on a K64 board, and is talking on one side with the mbed client or the border router drivers through the SPI (as the Atmel driver does) and on the other side with a PLC board. The PLC boards are connected through the electrical line.

 

I you can have a look to the registered trace files and let me know your advice, it will be great.

Thanks in advance for your help on this topic.
Best Regards
Nadine Sueur

[mbed_Client.pdf](https://github.com/ARMmbed/mbed-client/files/793633/mbed_Client.pdf)
[mbed_Border_Router.pdf](https://github.com/ARMmbed/mbed-client/files/793634/mbed_Border_Router.pdf)

**Comment by yogpan01** [comment]
Hi,
Based on the logs, mbedTLS handshake is timing out, 
MBEDTLS_ERR_SSL_TIMEOUT                           -0x6800
Looks like you are in a network which is too slow for completing DTLS handshake in a given time, which is around 2 minutes.

**Comment by NadineSueur** [comment]
Hi Yogesh,

Thanks for your answer.
I know that my network is slow, because currently all the functions in the PLC driver are done in software.
Is it possible to increase the time for completing the DTLS handshake ?

Thanks,
Nadine

**Comment by yogpan01** [comment]
Hi Nadine,
Look out for this file and line in your code
https://github.com/ARMmbed/mbed-client-mbed-tls/blob/master/source/m2mconnectionsecuritypimpl.cpp#L294

The maximum timeout is 29000 (29 seconds) which works like it starts from 10 sec, 20 secs, 30 secs and so one.. 
So, try to increase this to may be 100000 (100 seconds) if you think that would be good enough and check if DTLS handshake goes through.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1513

**Comment by NadineSueur** [comment]
Hi,

What do you mean by ARM Internal Ref: IOCTL-1513 ?

**Comment by yogpan01** [comment]
This is our automated internal ID for tracking this issue.

**Comment by JanneKiiskila** [comment]
@NadineSueur  - any luck in increasing the timeout?

**Comment by NadineSueur** [comment]
@JanneKiiskila  - No, and i'm a little discouraged
I have modified the file
https://github.com/ARMmbed/mbed-client-mbed-tls/blob/master/source/m2mconnectionsecuritypimpl.cpp#L294
as suggested by yogpan01, but the program can not connect to the mbed device anymore.

However, the ping IPv6 works from time to time.

**Comment by NadineSueur** [comment]
Finally, the program has displayed the message "Registered object successfully!"

So, connected to the mbed Device Connector, one can see that the device is connected, and Ican also access the endpoints.

The mbed client and server are connected through the electrical line. First, mbed client / server PLC application ?

I still have some questions, but I will open a new issue.

Thanks for your support.
Nadine

**Comment by JanneKiiskila** [comment]
Hi,

@NadineSueur - excellent to hear You got it working, what was the issue in the end? Ping should work always, if you have ping drops it means your connection is not stable and that will kill the TLS handshakes for sure.
