### ISSUE TITLE
In TLV (multiple instance resource) Integer or Boolean types are in string format. 

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#469]
According "OMA-TS-LightweightM2M-V1_0-20170208-A", Appendix c data Types:
Resource of the types Integer or Boolean within a TLV structure must be represented in a binary signed integer format. Currently it is in a string format.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1654

**Comment by JaniSuonpera** [comment]
Hi @EduardPon ,

I am now fixing this issue. Please see https://github.com/ARMmbed/mbed-client/pull/463.

Thank you & best regards,


Jani Suonperä

**Comment by EduardPon** [comment]
This is also planned to do for the Boolean resource type?
Resource type Time should be handled as an Integer type.

**Comment by JaniSuonpera** [comment]
Hi @EduardPon ,

Yes, this for resource types Boolean and Integer. I will add support also for resouce type Time.

Thank you & best regards,
Jani Suonperä

**Comment by JaniSuonpera** [comment]
This is now merged in 1.2 branch https://github.com/ARMmbed/mbed-client/pull/488 and master branch https://github.com/ARMmbed/mbed-client/pull/463. We can now close issue.
