### ISSUE TITLE
mbed client issue

### ISSUE THREAD

**Issue by anupam19** [ARMmbed/mbed-client#48]
I was exploring your mbed-client and got some issue on this. So let me explain what I did and the errors I am getting

1. I did git clone your mbed-client
2. installed yotta
3. inside mbed-client directory, executed yotta update and then yotta list --all

mbed-client 1.0.1
┣─ mbed-client-c 1.0.1
┃ ┗─ nanostack-libservice 3.0.4 yotta_modules/nanostack-libservice
┣─ mbed-client-linux 1.0.1
┗─ mbed-client-mbedtls 1.0.2
  ┗─ mbedtls 2.0.7 yotta_modules/mbedtls
5. ls
anupam@anupam:~/Dev/mbed-client$ ls
doxygen   include_dirs.mk  LICENSE   mbed-client  porting-guide.md  run_unit_tests.sh  sources.mk  version_check.sh  yotta_modules
config  Howto.md  junit_xsl.xslt   Makefile  module.json  README.md         source             test        xsl_script.sh     yotta_targets

4. then executed yotta target x86-linux-native
5. then cd yotta_targets/x86-linux-native/
6. then executed yotta link-target
7. cd  back to anupam@anupam:~/Dev/mbed-client$
8. executed yotta target x86-linux-native
9. executed yotta build
10. according to docs build dir will be created
anupam@anupam:~/Dev/mbed-client/build/x86-linux-native/test$ ls
CMakeFiles  cmake_install.cmake  CTestTestfile.cmake
But no hello prog is there.

rather I found here :
anupam@anupam:~/Dev/mbed-client/test$ ls
CMakeLists.txt  helloworld-mbedclient  lwm2mtestapplication  mbedclient  mbedclient_linux  mbedclient-smokeTest

I tried to test hello prog there but got error : 
main.cpp:43:22: fatal error: ns_trace.h: No such file or directory
 #include "ns_trace.h"
                      ^
compilation terminated.
make: *** [main.o] Error 1

Please explain

**Comment by yogpan01** [comment]
Can you please explain which OS environment are you trying to build mbed-client ?
Also, much easier to configure mbed-client through some example application , check this section 
http://www.mbed.com/en/development/software/mbed-client/
There is an example application for Linux platform https://github.com/ARMmbed/mbed-client-linux-example

**Comment by yogpan01** [comment]
There is a disclaimer in the README https://github.com/ARMmbed/mbed-client-linux-example/blob/master/README.md
The Device Connector Service is not yet live , for more information you can check mbed.com
