### ISSUE TITLE
Server callback cannot cope with COAP_STATUS_BUILDER_MESSAGE_SENDING_FAILED

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#499]
In m2mnsdlinterface.cpp the function received_from_server_callback, the CoAP status must be checked in case the status becomes COAP_STATUS_BUILDER_MESSAGE_SENDING_FAILED. 

A possible scenario:
We have a standalone Leshan server and use it with PSK security to communicate with the mbed-client. If this server is restarted, it expects the clients to perform a DTLS handshake first. But clients are not aware about this restart and will do one a while a registration update. The update message send to the server will be ignored by the server and hereby not confirmed. The clients CoAP proces will perform re-sends that all will fail. Finally the function received_from_server_callback is called by CoAP, signaling in the coap_header->coap_status COAP_STATUS_BUILDER_MESSAGE_SENDING_FAILED.

Now in this case a full registration including security should be initiated.

**Comment by yogpan01** [comment]
Hi,
The logic to fallback to full registration is already here 
https://github.com/ARMmbed/mbed-client/blob/master/source/m2mnsdlinterface.cpp#L411

**Comment by EduardPon** [comment]
I'n not sure, but for each CoAP re-send the msg_id seems to be increment. So the msg_id in the CoAP header will not match the initial msg_id of the update.

`     } else if(coap_header->msg_id == nsdl_handle->update_register_msg_id) {`

**Comment by yogpan01** [comment]
Resending logic for CoAP message is not incrementing msg_id . It tries to send the same message based on retransmission parameters and it tracks the counter for that message through msg_id , so incrementing msg_id will make it a different message and the internal list will not be able to track the number of times the message has been tried to send.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1732

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
