### ISSUE TITLE
Inability to assess and use this library intuitively

### ISSUE THREAD

**Issue by 40Grit** [ARMmbed/mbed-client#503]
* This particular repository and software module is called mbed-client.

* It is described in  the readme as "a library that connects to mbed Device Connector Service, mbed Device Server (mDS)", etc...

* The introduction of the "ARM mbed Client Guide" says 
, "The mbed Client high-level APIs allow mbed OS developers to create applications with LWM2M features as described in the Lightweight Machine to Machine Technical Specification"

* Most of the file, function, and type names start with the following three characters, "m2m"

I beleive those points have reduced my ability to determine the limitations and operation of this library.

* Is this actually meant to be an LWM2M compliant client? Or does it just allow connecting to mDS etc...

* Is "m2m" short for LWM2M? If so; I use a modern IDE, have plenty of hard drive space, and would greatly prefer "lwm2m" in place of just "m2m" for name prefixes. This might prove more intuitive and increase clarity.

* If this is meant to be LWM2M compliant and thus able to connect to any LWM2M compliant server, wouldn't mbedLwm2mClient be a more suitable library name and naming prefix?

Regardless of whether these obfuscations are purposeful due to business reasoning, I predict they will decrease adoption rate.

Please keep it clean, keep it open, and please please please don't abreviate anything unless there is a well recognized accronym.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1804

**Comment by yogpan01** [comment]
Thanks for the feedback.
M2M keyword is for legacy reason before we made this library public. We are constantly working on improving and aligning our implementation with LWM2M spec and if there are any mismatches, please report them, we are fixing those issues regularly.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
