### ISSUE TITLE
Return 4.08 Request Entity Incomplete on Block transfer errors

### ISSUE THREAD

**Issue by ghseb** [ARMmbed/mbed-client#512]
If an ongoing blocktransfer (Block 1 option) is interrupted by one out of order Block (e.g. when using UDP) this is not recognized by mbed-client and no error 4.08 Request Entity Incomplete is returned as specified in the coap specification. The result is that the block transfer goes on and the client who PUTs new Blocks is never informed about the error.

I see two possible solutions. First mbed client could check strictly increasing block numbers by itself and return an error if necessary. Second is that the user gets a possibility to notify mbed-client about an error which then should return `COAP_MSG_CODE_RESPONSE_REQUEST_ENTITY_INCOMPLETE`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1885

**Comment by yogpan01** [comment]
Hi @ghseb , can you please verify if this patch fixes the issue https://github.com/ARMmbed/mbed-coap/pull/28 ?

**Comment by ghseb** [comment]
Sorry for the late reply. 
Well this patch seems to fix cases where no external blockwise storage is used. But if external blockwise storage is enabled the current block seems to be removed from the list of received blockwise payloads immediately because it is passed to the user. In this case searching the list of received blockwise payloads never finds a match and COAP_MSG_CODE_RESPONSE_REQUEST_ENTITY_INCOMPLETE is returned even if the correct block was received.

Maybe it would be sufficient to save the block number of the block that was received last and return REQUEST_ENTITY_INCOMPLETE if the block number of the current block is lower or higher than expected. 

if(current_block_number != last_block_number || // Block duplicated
       current_block_number != last_block_number + 1)

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.
 
Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.
 
Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
