### ISSUE TITLE
How to use ReportHandler?

### ISSUE THREAD

**Issue by amq** [ARMmbed/mbed-client#519]
It seems to be really powerful with timers and margins, but lacks documentation.

For example, I'd like to send data to the server at most once per second. For this I could set `_attribute_state=2` and `_pmin=1.0f`, but how do I do this from my application?

**Comment by teetak01** [comment]
Hi @amq you are not supposed to control those from the application side, but from the REST via LWM2M server. Client implements the LWM2M resource handling attributes.

Use REST PUT to use Write attributes to define any of the attributes (Like pmin or pmax). The start subscription on that resource.

For ex. PUT /endpoint/object/object_instance/resource?pmax=60

https://docs.mbed.com/docs/mbed-device-connector-web-interfaces/en/latest/api-reference/#subscriptions

https://docs.mbed.com/docs/mbed-device-connector-web-interfaces/en/latest/
