### ISSUE TITLE
Deprecated In Subject

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/mbed-client#525]
If this is deprecated can the subject be repository subject be changed to deprecated?
Along with any other deprecated repo's under ARMmbed.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2591

**Comment by teetak01** [comment]
@loverdeg-ep Hi, just went through the legacy-component libraries and added deprecation notices.

**Comment by 0Grit** [comment]
@teetak01 

Thanks, can't tell you how many times I accidentally searched or clicked into these.

**Comment by 0Grit** [comment]
@teetak01 These deprecated repositories still come up in my searches and confuse new Mbed/Pelion devs.

Any chance they can be 'archived'?

**Comment by teetak01** [comment]
Sure. I will make a note of it.
