### ISSUE TITLE
Unable to handle the payload of a POST request

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-client#55]
By the looks of how you handle the POST requests https://github.com/ARMmbed/mbed-client/blob/master/source/m2mresourceinstance.cpp#L384

I saw that there is no possibility to access the payload. Isn't it supposed to be accessible according to the LWM2M specification?

**Comment by yogpan01** [comment]
From the application level, you should receive the callback in value_updated() (check M2MInterfaceObserver class ) which should inform about this.

**Comment by javier-moreno-tridonic-com** [comment]
Thanks for the quick answer! 

I see that clearly in the case of a PUT request. But in the handling of the POST request I don't see any calls to the "value_updated()" callback. Also i don't see any calls to "M2MResourceInstance::report()" or to "M2MResourceInstance::set_value()" that can also trigger the callback. Could you please point me how the "handle_post_request()" triggers it?

Thank you once more for your time.

**Comment by yogpan01** [comment]
That's because POST in context of resource means EXECUTE and not update. If you want to update some value for resource , use PUT and it will update the resource value.

**Comment by javier-moreno-tridonic-com** [comment]
Agreed, but nevertheless the LWM2M technical specification states the following:

*A Resource is Executed by sending a CoAP POST to the corresponding path. The request MAY include the value (e.g. as a String) in the payload reresenting the arguments of the “Execute” operation. Note that the behaviour of the “Execute” operation, whether it uses arguments and how those are interpreted, and how it returns values is specified in the Resource description of the Object.*

Even the *4.00 Bad Request* response code for an execute has associated the reason phrase:

*The LWM2M Server doesn’t understand the argument in the payload*

I our case we don't intend to use POST requests to update values, but to pass arguments to our resources

**Comment by yogpan01** [comment]
Yes, you are right you can pass argument as payload. I will check the implementation and fix it.
You can then access the payload by passing function in the set_execute_function(execute_callback callback) where you would receive the payload as argument.

**Comment by javier-moreno-tridonic-com** [comment]
Cool! Thank you!

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTCLT-273

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-362

**Comment by yogpan01** [comment]
Hi, We have fixed this issue and are now verifying the fix. The fix is also available for you to test and provide feedback  if it resolves your issue. You can get the latest changes by updating the yotta module.

**Comment by yogpan01** [comment]
Hi, Can you take the latest update of this package and verify if its working fine for you ?

**Comment by javier-moreno-tridonic-com** [comment]
Sorry for the delay. I managed to finally test it and so far is working fine for me.
