### ISSUE TITLE
Reliance on EthernetInterface breaks compilation for 6LoWPAN

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client#59]
A test of mbed-client relies on the fact that EthernetInterface is there: https://github.com/ARMmbed/mbed-client/blob/master/test/mbedclient-smokeTest/main.cpp#L17

This is unnecessarily pulled in by sal for the K64F because it defined lwip in target.json of frdm-k64f-gcc, while this should actually be in a config of an application that requires it.

Should the test code be compiled at all for the 6lowpan example?

**Comment by yogpan01** [comment]
Hi, thanks for reporting. We will investigate the issue and keep you informed.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTCLT-272

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-361

**Comment by yogpan01** [comment]
This is handled through following PRs https://github.com/ARMmbed/sal/pull/28 and https://github.com/ARMmbed/mbed-client-example-6lowpan/commit/9de811b23e45571e76fd099f5646b3636b18a36d.
