### ISSUE TITLE
Support single Server / server with supporting ARMmbed/mbed-client

### ISSUE THREAD

**Issue by sirrko** [ARMmbed/mbed-client#67]
Hi guys, 
could you please give me few answers?
1. Why ARMmbed/mbed-client supports only one-to-one client-server registration?
2. I tried to connect ARMmbed/mbed-client with wakaama test server, but last are not so improved. Could you please tell me where I can find test-server with full supporting of ARMmbed/mbed-client? Or maybe you have some complete and open-source? 
Thank you!

**Comment by yogpan01** [comment]
Hi, mbed-client should be able to connect to any server. We will look into this issue as to why it is not connecting to Wakamma server. Thanks for reporting.

**Comment by sirrko** [comment]
Look like test "mbedclient_linux" can not connects to local Leshan server.

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTCLT-370
