### ISSUE TITLE
PSK support

### ISSUE THREAD

**Issue by lotuseater24** [ARMmbed/mbed-client#77]
Hello,
may you please tell me, whether Pre-Shared Key security mode for communication between the Client and Server is supported? 
It seems, that mbedtls supports all what needed for that, but mbed-client still doesn't support PSK.
Is that correct?

Best regards.

**Comment by yogpan01** [comment]
Yes it is supported.

**Comment by lotuseater24** [comment]
Thanks. Just saw in test the following commented out code:
/* Not used now because there is no TLS or DTLS implementation available for stack.
security->set_resource_value(M2MSecurity::ServerPublicKey,certificates->certificate_ptr[0],certificates->certificate_len[0]);     security->set_resource_value(M2MSecurity::PublicKey,certificates->certificate_ptr[1],certificates->certificate_len[1]);
security->set_resource_value(M2MSecurity::Secretkey,certificates->own_private_key_ptr,certificates->own_private_key_len);
*/

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-385
