### ISSUE TITLE
heap memory requirement

### ISSUE THREAD

**Issue by brianjang** [ARMmbed/mbed-client#86]
could you provide the memory requirement for mbed-client module?
ex. text, bss, stack, heap size.

i want to choose a dev-board base on the memory requirement.

**Comment by yogpan01** [comment]
Hi, Please refer to the example application here https://github.com/ARMmbed/mbed-client-linux-example
We support FRDM-K64F board as dev-board.

**Comment by brianjang** [comment]
Hi,

i think mbed-client module need much heap memory.
my device's heap memory is about 25KB but this is not enough!
(i created 8 object as below.
M2MDevice* create_device_object() {
        // Creates device object which contains mandatory resources linked with
        // device endpoint.
        M2MDevice *device = M2MInterfaceFactory::create_device();
        if(device) {
            device->create_resource(M2MDevice::Manufacturer,MANUFACTURER);
            device->create_resource(M2MDevice::DeviceType,TYPE);
            device->create_resource(M2MDevice::ModelNumber,MODEL_NUMBER);
            device->create_resource(M2MDevice::SerialNumber,SERIAL_NUMBER);
			device->create_resource(M2MDevice::HardwareVersion,HW_VERSION);
            device->create_resource(M2MDevice::FirmwareVersion,FW_VERSION);
            device->create_resource(M2MDevice::SoftwareVersion,SW_VERSION);
            device->create_resource(M2MDevice::MemoryTotal,MEMORY_TOTAL);
        }
        return device;
    }

=> could you give the information for heap usage?
( i am using 32KB SRAM device - i don't use TLS feature, only use non-secure UDP)
