### ISSUE TITLE
heap usage of mbed-client module

### ISSUE THREAD

**Issue by brianjang** [ARMmbed/mbed-client#87]
Hi,

i think mbed-client module need much heap memory.
my device's heap memory is about 25KB but this is not enough!
(i created 8 object as below.
M2MDevice\* create_device_object() {
// Creates device object which contains mandatory resources linked with
// device endpoint.
M2MDevice *device = M2MInterfaceFactory::create_device();
if(device) {
device->create_resource(M2MDevice::Manufacturer,MANUFACTURER);
device->create_resource(M2MDevice::DeviceType,TYPE);
device->create_resource(M2MDevice::ModelNumber,MODEL_NUMBER);
device->create_resource(M2MDevice::SerialNumber,SERIAL_NUMBER);
device->create_resource(M2MDevice::HardwareVersion,HW_VERSION);
device->create_resource(M2MDevice::FirmwareVersion,FW_VERSION);
device->create_resource(M2MDevice::SoftwareVersion,SW_VERSION);
device->create_resource(M2MDevice::MemoryTotal,MEMORY_TOTAL);
}
return device;
}

=> could you give the information for heap usage?
( i am using 32KB SRAM device - i don't use TLS feature, only use non-secure UDP)

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-395

**Comment by brianjang** [comment]
if i modify the below 2parts then i can run 8-ojbects (it means heap usage is able to be reduced).
=> could you check this point?

Modified position : 
1. Minar.cpp : 
#ifndef YOTTA_CFG_MINAR_INITIAL_EVENT_POOL_SIZE
#define YOTTA_CFG_MINAR_INITIAL_EVENT_POOL_SIZE      4 //50
#endif
#ifndef YOTTA_CFG_MINAR_ADDITIONAL_EVENT_POOLS_SIZE
#define YOTTA_CFG_MINAR_ADDITIONAL_EVENT_POOLS_SIZE 4 //100

2. M2mvector.h
MORE_SIZE = 4 //32

**Comment by brianjang** [comment]
or is there any way to limit heap usage of mbed-client as below?:

#define APP_DEFINED_HEAP_SIZE 13000
static uint8_t app_stack_heap[APP_DEFINED_HEAP_SIZE +1];

ns_dyn_mem_init(app_stack_heap, APP_DEFINED_HEAP_SIZE, app_heap_error_handler,0);

**Comment by yogpan01** [comment]
Hi,
Thanks for your input on reducing heap usage. We are also in study phase to identify areas of reducing memory footprints for mbed-client. Currently the biggest memory consumption is happening with mbedTLS and there are other parts in mbed-client library which can be optimized for further memory optimization. We will keep you informed in upcoming releases where we will be optimizing our memory size.
