### ISSUE TITLE
Unregistration failed

### ISSUE THREAD

**Issue by BenGant** [ARMmbed/mbed-client#89]
I try to connect to leshan server in PSK security mode using modified example for mbedclient_linux. During first session everything is fine, but after that unregister failed. In nonsecure mode all work's correctly.
http://pastebin.com/m5RG7TNm

**Comment by BenGant** [comment]
I've enabled dtls logging and got some extended info about error:
[dtls_log.txt](https://github.com/ARMmbed/mbed-client/files/33096/dtls_log.txt)

**Comment by AnttiKauppila** [comment]
ARM Internal Ref: IOTCLT-412

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-417
