### ISSUE TITLE
According to M2Mspecification Registration update is performed by sending a CoAP PUT

### ISSUE THREAD

**Issue by lotuseater24** [ARMmbed/mbed-client#90]
According to M2M specification Registration update is performed by sending a CoAP PUT.
While in yotta_modules/mbed-client-c/source/libNsdl/src/sn_nsdl.c it can be seen that POST is used instead - line 398;
register_message_ptr->msg_code = COAP_MSG_CODE_REQUEST_POST;

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTCLT-416

**Comment by yogpan01** [comment]
Hi, as per the updated specifications, the Registration Update message is changed from PUT to POST. The same can be tested against Device Connector service.
