### ISSUE TITLE
Create operation fails due to unrecognised content type.

### ISSUE THREAD

**Issue by lotuseater24** [ARMmbed/mbed-client#96]
Tested with Leshan server. When I try to create an object instance with CREATE operation, it fails, as mbed client doesn't recognise the content type in M2MObject::handle_post_request.
Server passes 1542 as content type code (that is TLV).
While mbed_client recognises 99 as TLV (constant COAP_CONTENT_OMA_TLV_TYPE in m2mcontsants.h which also has type uint8_t that is too small to contain 1542).

May you consider using 1542 instead of 99 as identifier of TLV? 
At least, it seems logical to change its type to uint16_t, because received format may be 2 bytes long.

**Comment by yogpan01** [comment]
Hi,
The TLV content format type used in connector.mbed.com is 99 and mbed-client is following that as Content type for TLV.
However, we will consider to increase the range for accepting content-type format from one byte to four byte to accomodate future content-format type.

**Comment by lotuseater24** [comment]
Thanks.

**Comment by EduardPon** [comment]
Hello yogpan01,

Any progress on the create of instances accepting TLV content type 1542?
We want to use the Leshan server to do the create. 

Thanks in advance.

**Comment by yogpan01** [comment]
Hi,
Not progress yet on this.
