### ISSUE TITLE
Getting the static resource value

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client#97]
When I run the mbed-client-linux-example with the Device Connector, and I try this REST API in the API console:
https://ds-test-sl.dev.mbed.com/endpoints/2a28ddd6-682a-4ffa-b134-be69fcba1472/Test/0/S

I am getting this error message
Server response: 412 (Precondition Failed) No notification channel found.

Is there a way to fetch the static resource value? Thanks.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-426

**Comment by yogpan01** [comment]
Please use the REST API URL from Device Connector. The URL address is api.connector.mbed.com
