### ISSUE TITLE
Needs a readme

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/mbed-client#99]
This module needs a readme.md file that at least links to documentation elsewhere if not giving some simple usage examples itself.

**Comment by yogpan01** [comment]
README is under docs folder. The documentation is generated from there and is available in docs.mbed.com

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-425

**Comment by yogpan01** [comment]
There is now a README at github which re-directs to the official mbed-client documentation site. We will be updating more information on this in coming releases.
